# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: "Log level"
        required: true
        default: "warning"
  push:
    branches: [ master, develop, feature/ci ]
  schedule:
    # min hour(UTC) day month week[0(sun)-6(sat)]
    # */1 17:00 , run
    - cron:  "0 8 1 * *"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Make config file
      run: |
        python EncryptConfig.py --path="./encrypt.ini" --key="${{ secrets.SECRET_KEY }}"
        dir
      working-directory: ./.github\workflows

    - name: Move config file
      run: |
        copy decrypt.ini ../../config/config.ini
        cd ../../config/
        dir
      working-directory: ./.github\workflows

    - name: Test with unittest
      run: |
        dir
        python -m unittest
      working-directory: ./
